title: "XDomainMark"
description: "[One-sentence contribution placeholder]"
markdown: kramdown
url: ""
baseurl: ""

url: "https://smiledra.github.io"
baseurl: "/xdomainmark"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
